# -*- coding: utf-8 -*-
"""Actividad multilistas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y_8kdYEDA34EYW4LeiJRXaHlwZ0u-ril
"""

#Crear un programa que realice la multiplicación de dos matrices. Tener en cuenta las validaciones que deben hacerse para realizar la operación.

def multiplicar_matrices(a, b):
 
    if len(a[0]) != len(b):
        raise ValueError("Las matrices deben ser del mismo tamaño")
    resultado = []
    for i in range(len(a)):
        fila = []
        for j in range(len(b[0])):
            suma = 0
            for k in range(len(b)):
                suma += a[i][k] * b[k][j]
            fila.append(suma)
        resultado.append(fila)
    return resultado

# Ejemplo
matriz_a = [[1, 2], [3, 4], [5, 6]]
matriz_b = [[7, 8, 9], [10, 11, 12]]
resultado = multiplicar_matrices(matriz_a, matriz_b)
print("El resultado de la multiplicación es: ", resultado)

#Almacenar en una lista los datos de 5 empleados, cada elemento de la lista es una sub lista con el nombre del empleado junto a sus últimos tres sueldos. 
#El programa debe tener las siguientes funciones:
#Carga de los nombres de empleados y sus últimos tres sueldos.
#Imprimir el monto total cobrado por cada empleado.​


def cargar_empleados():
   
    empleados = []
    for i in range(5):
        nombre = input("Ingrese el nombre del empleado {}: ".format(i+1))
        sueldos = []
        for j in range(3):
            sueldo = float(input("Ingrese el sueldo {}: ".format(j+1)))
            sueldos.append(sueldo)
        empleados.append([nombre] + sueldos)
    return empleados

def imprimir_totales(empleados):
   
    for empleado in empleados:
        total = sum(empleado[1:])
        print("El empleado {} cobró un total de {}.".format(empleado[0], total))

empleados = cargar_empleados()
imprimir_totales(empleados)

#Utilizar una multilista para cargar los votos obtenidos por tres candidatos a una elección de gobernador. 
#Se debe almacenar el nombre del candidato, el municipio (5 municipios en total) y el total de votos. 
#Realizar un programa que realice lo siguiente: 
#Solicitar los nombres de los candidatos, el municipio y la cantidad de votos obtenidos.
#Imprimir el total de votos de un candidato solicitado.
#Imprimir el total de votos en un municipio solicitado.
#Imprimir el candidato ganador.

def cargar_votos():
   
    candidatos = []
    for i in range(3):
        nombre = input("Ingrese el nombre del candidato {}: ".format(i+1))
        candidatos.append([nombre, []])
        for j in range(5):
            municipio = input("Ingrese el nombre del municipio {}: ".format(j+1))
            votos = int(input("Ingrese la cantidad de votos obtenidos por el candidato en el municipio: "))
            candidatos[i][1].append([municipio, votos])
    return candidatos

def total_votos_candidato(candidatos, nombre_candidato):
  
    total = 0
    for candidato in candidatos:
        if candidato[0] == nombre_candidato:
            for municipio in candidato[1]:
                total += municipio[1]
            break
    return total

def total_votos_municipio(candidatos, nombre_municipio):

    total = 0
    for candidato in candidatos:
        for municipio in candidato[1]:
            if municipio[0] == nombre_municipio:
                total += municipio[1]
                break
    return total

def candidato_ganador(candidatos):
    
    max_votos = 0
    nombre_ganador = ''
    for candidato in candidatos:
        total = 0
        for municipio in candidato[1]:
            total += municipio[1]
        if total > max_votos:
            max_votos = total
            nombre_ganador = candidato[0]
    return nombre_ganador

candidatos = cargar_votos()

nombre_candidato = input("Ingrese el nombre del candidato para obtener su total de votos: ")
total = total_votos_candidato(candidatos, nombre_candidato)
print("El total de votos obtenidos por el candidato {} es: {}".format(nombre_candidato, total))

nombre_municipio = input("Ingrese el nombre del municipio para obtener su total de votos: ")
total = total_votos_municipio(candidatos, nombre_municipio)
print("El total de votos obtenidos en el municipio {} es: {}".format(nombre_municipio, total))

ganador = candidato_ganador(candidatos)
print("El candidato ganador es: {}".format(ganador))